<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

use App\Models\UserProfile;
use App\Models\User;
use App\Models\Activity;
use App\Models\CausingCase;
use App\Models\Country;
use App\Models\Role;
class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
		DB::transaction(function (){

			///** create profile */
            //$userprofile = UserProfile::create([
			//	'gender'  => 'M',
			//	'first_name' => 'Admin',
			//	'last_name' => 'Admin',
			//	'file_name' => 'default',
		    //    'file_path' => 'default'
			//]);

			///** create user */
			//$user = $userprofile->user()->create([
			//	'name' => 'admin',
			//	'role'=>'ADMIN',
			//	'email' => 'admin@gmail.com',
			//	'password' => Hash::make('password')
			//]);
			
			///** create activity */
			//$activityCodes = ['001','002'];
			//$activityNames =['ការវាយប្រហារ','ការបង្ក្រាប'];
			//for($i=0;$i<2;$i++){
			//	Activity::create([
			//		'code'=>$activityCodes[$i],
			//		'name'=>$activityNames[$i]
			//	]);
			//}

			///** create Causing Case */
			//$causingCaseCodes = ['001','002'];
			//$causingCaseName =['គ្រាប់បែកបង្កប់','បាញ់គ្នាប្រហារ'];
			//for($i=0;$i<2;$i++){
			//	CausingCase::create([
			//		'code'=>$causingCaseCodes[$i],
			//		'name'=>$causingCaseName[$i]
			//	]);
			//}

			

			/** Setup countries */
			$this->seedCountries();
			
        });
    }
	private function seedCountries(){
			/** Create country */
			$countryCodes = $this->countryCode();
			$countryNameENGS=$this->countryENG();
			for($i=0;$i<collect($countryNameENGS)->count();$i++){
				$existCountry = Country::where('code',$countryCodes[$i])->first();
				if(!$existCountry){
					Country::create([
						'code'=>$countryCodes[$i],
						'name_eng'=>$countryNameENGS[$i],
						'name_kh'=>$countryNameENGS[$i]
					]);
				}
				
			}
	}
	private function countryENG(){
		return [
			'Afghanistan',
			'Albania',
			'Algeria',
			'American Samoa',
			'Andorra',
			'Angola',
			'Anguilla',
			'Antarctica',
			'Antigua and Barbuda',
			'Argentina',
			'Armenia',
			'Aruba',
			'Australia',
			'Austria',
			'Azerbaijan',
			'Bahamas',
			'Bahrain',
			'Bangladesh',
			'Barbados',
			'Belarus',
			'Belgium',
			'Belize',
			'Benin',
			'Bermuda',
			'Bhutan',
			'Bolivia',
			'Bosnia and Herzegovina',
			'Botswana',
			'Brazil',
			'British Indian Ocean Territory',
			'British Virgin Islands',
			'Brunei',
			'Bulgaria',
			'Burkina Faso',
			'Burundi',
			'Cambodia',
			'Cameroon',
			'Canada',
			'Cape Verde',
			'Cayman Islands',
			'Central African Republic',
			'Chad',
			'Chile',
			'China',
			'Christmas Island',
			'Cocos Islands',
			'Colombia',
			'Comoros',
			'Cook Islands',
			'Costa Rica',
			'Croatia',
			'Cuba',
			'Curacao',
			'Cyprus',
			'Czech Republic',
			'Democratic Republic of the Congo',
			'Denmark',
			'Djibouti',
			'Dominica',
			'Dominican Republic',
			'East Timor',
			'Ecuador',
			'Egypt',
			'El Salvador',
			'Equatorial Guinea',
			'Eritrea',
			'Estonia',
			'Ethiopia',
			'Falkland Islands',
			'Faroe Islands',
			'Fiji',
			'Finland',
			'France',
			'French Polynesia',
			'Gabon',
			'Gambia',
			'Georgia',
			'Germany',
			'Ghana',
			'Gibraltar',
			'Greece',
			'Greenland',
			'Grenada',
			'Guam',
			'Guatemala',
			'Guernsey',
			'Guinea',
			'Guinea-Bissau',
			'Guyana',
			'Haiti',
			'Honduras',
			'Hong Kong',
			'Hungary',
			'Iceland',
			'India',
			'Indonesia',
			'Iran',
			'Iraq',
			'Ireland',
			'Isle of Man',
			'Israel',
			'Italy',
			'Ivory Coast',
			'Jamaica',
			'Japan',
			'Jersey',
			'Jordan',
			'Kazakhstan',
			'Kenya',
			'Kiribati',
			'Kosovo',
			'Kuwait',
			'Kyrgyzstan',
			'Laos',
			'Latvia',
			'Lebanon',
			'Lesotho',
			'Liberia',
			'Libya',
			'Liechtenstein',
			'Lithuania',
			'Luxembourg',
			'Macau',
			'Macedonia',
			'Madagascar',
			'Malawi',
			'Malaysia',
			'Maldives',
			'Mali',
			'Malta',
			'Marshall Islands',
			'Mauritania',
			'Mauritius',
			'Mayotte',
			'Mexico',
			'Micronesia',
			'Moldova',
			'Monaco',
			'Mongolia',
			'Montenegro',
			'Montserrat',
			'Morocco',
			'Mozambique',
			'Myanmar',
			'Namibia',
			'Nauru',
			'Nepal',
			'Netherlands',
			'Netherlands Antilles',
			'New Caledonia',
			'New Zealand',
			'Nicaragua',
			'Niger',
			'Nigeria',
			'Niue',
			'North Korea',
			'Northern Mariana Islands',
			'Norway',
			'Oman',
			'Pakistan',
			'Palau',
			'Palestine',
			'Panama',
			'Papua New Guinea',
			'Paraguay',
			'Peru',
			'Philippines',
			'Pitcairn',
			'Poland',
			'Portugal',
			'Puerto Rico',
			'Qatar',
			'Republic of the Congo',
			'Reunion',
			'Romania',
			'Russia',
			'Rwanda',
			'Saint Barthelemy',
			'Saint Helena',
			'Saint Kitts and Nevis',
			'Saint Lucia',
			'Saint Martin',
			'Saint Pierre and Miquelon',
			'Saint Vincent and the Grenadines',
			'Samoa',
			'San Marino',
			'Sao Tome and Principe',
			'Saudi Arabia',
			'Senegal',
			'Serbia',
			'Seychelles',
			'Sierra Leone',
			'Singapore',
			'Sint Maarten',
			'Slovakia',
			'Slovenia',
			'Solomon Islands',
			'Somalia',
			'South Africa',
			'South Korea',
			'South Sudan',
			'Spain',
			'Sri Lanka',
			'Sudan',
			'Suriname',
			'Svalbard and Jan Mayen',
			'Swaziland',
			'Sweden',
			'Switzerland',
			'Syria',
			'Taiwan',
			'Tajikistan',
			'Tanzania',
			'Thailand',
			'Togo',
			'Tokelau',
			'Tonga',
			'Trinidad and Tobago',
			'Tunisia',
			'Turkey',
			'Turkmenistan',
			'Turks and Caicos Islands',
			'Tuvalu',
			'U.S. Virgin Islands',
			'Uganda',
			'Ukraine',
			'United Arab Emirates',
			'United Kingdom',
			'United States',
			'Uruguay',
			'Uzbekistan',
			'Vanuatu',
			'Vatican',
			'Venezuela',
			'Vietnam',
			'Wallis and Futuna',
			'Western Sahara',
			'Yemen',
			'Zambia',
			'Zimbabwe'
		];
	}
	private function countryCode(){
		return [
				'AF',
				'AL',
				'DZ',
				'AS',
				'AD',
				'AO',
				'AI',
				'AQ',
				'AG',
				'AR',
				'AM',
				'AW',
				'AU',
				'AT',
				'AZ',
				'BS',
				'BH',
				'BD',
				'BB',
				'BY',
				'BE',
				'BZ',
				'BJ',
				'BM',
				'BT',
				'BO',
				'BA',
				'BW',
				'BR',
				'IO',
				'VG',
				'BN',
				'BG',
				'BF',
				'BI',
				'KH',
				'CM',
				'CA',
				'CV',
				'KY',
				'CF',
				'TD',
				'CL',
				'CN',
				'CX',
				'CC',
				'CO',
				'KM',
				'CK',
				'CR',
				'HR',
				'CU',
				'CW',
				'CY',
				'CZ',
				'CD',
				'DK',
				'DJ',
				'DM',
				'DO',
				'TL',
				'EC',
				'EG',
				'SV',
				'GQ',
				'ER',
				'EE',
				'ET',
				'FK',
				'FO',
				'FJ',
				'FI',
				'FR',
				'PF',
				'GA',
				'GM',
				'GE',
				'DE',
				'GH',
				'GI',
				'GR',
				'GL',
				'GD',
				'GU',
				'GT',
				'GG',
				'GN',
				'GW',
				'GY',
				'HT',
				'HN',
				'HK',
				'HU',
				'IS',
				'IN',
				'ID',
				'IR',
				'IQ',
				'IE',
				'IM',
				'IL',
				'IT',
				'CI',
				'JM',
				'JP',
				'JE',
				'JO',
				'KZ',
				'KE',
				'KI',
				'XK',
				'KW',
				'KG',
				'LA',
				'LV',
				'LB',
				'LS',
				'LR',
				'LY',
				'LI',
				'LT',
				'LU',
				'MO',
				'MK',
				'MG',
				'MW',
				'MY',
				'MV',
				'ML',
				'MT',
				'MH',
				'MR',
				'MU',
				'YT',
				'MX',
				'FM',
				'MD',
				'MC',
				'MN',
				'ME',
				'MS',
				'MA',
				'MZ',
				'MM',
				'NA',
				'NR',
				'NP',
				'NL',
				'AN',
				'NC',
				'NZ',
				'NI',
				'NE',
				'NG',
				'NU',
				'KP',
				'MP',
				'NO',
				'OM',
				'PK',
				'PW',
				'PS',
				'PA',
				'PG',
				'PY',
				'PE',
				'PH',
				'PN',
				'PL',
				'PT',
				'PR',
				'QA',
				'CG',
				'RE',
				'RO',
				'RU',
				'RW',
				'BL',
				'SH',
				'KN',
				'LC',
				'MF',
				'PM',
				'VC',
				'WS',
				'SM',
				'ST',
				'SA',
				'SN',
				'RS',
				'SC',
				'SL',
				'SG',
				'SX',
				'SK',
				'SI',
				'SB',
				'SO',
				'ZA',
				'KR',
				'SS',
				'ES',
				'LK',
				'SD',
				'SR',
				'SJ',
				'SZ',
				'SE',
				'CH',
				'SY',
				'TW',
				'TJ',
				'TZ',
				'TH',
				'TG',
				'TK',
				'TO',
				'TT',
				'TN',
				'TR',
				'TM',
				'TC',
				'TV',
				'VI',
				'UG',
				'UA',
				'AE',
				'GB',
				'US',
				'UY',
				'UZ',
				'VU',
				'VA',
				'VE',
				'VN',
				'WF',
				'EH',
				'YE',
				'ZM',
				'ZW'
		];
	}
}